version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile 
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL = "amqp://myuser:mypassword@rabbitmq:5672//"
      - CELERY_BACKEND = "rpc://"
      - MONGO_URI = "mongodb://mongo:27017/timerdb"
    depends_on:
      - rabbitmq
      - redis
      - mongo
    ports:
      - "8000:80"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypassword

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"  

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    command: celery -A src.celery_workers.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL = "amqp://myuser:mypassword@rabbitmq:5672//"
      - CELERY_RESULT_BACKEND = "rpc://"
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./:/app

  mongo:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "27017:27017"  # MongoDB port
    volumes:
      - mongo-data:/data/db  # Persistent volume for MongoDB data

volumes:
  mongo-data:
     
