FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV ENVIRONMENT=local

WORKDIR /app

COPY requirements/local.txt local-requirements.txt
RUN pip install --no-cache-dir -r local-requirements.txt && rm local-requirements.txt

COPY . .

RUN chmod -R 777 /app/logs/project.log
USER root

CMD ["celery", "-A", "src.celery_workers.celery_app", "worker", "--loglevel=info", "--queues=webhook_queue"]
